
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: my-django-app-container
  replicas: 4
  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-django-app-container
    spec:
      containers:
      - image: haroonniamat029/django-app:latest
        imagePullPolicy: Always
        name: my-django-app-container
        ports:
        - containerPort: 8000
          protocol: TCP
      
---
apiVersion: v1
kind: Service
metadata:
  name: my-django-app-service
spec:
  selector:
      app.kubernetes.io/name: my-django-app-container
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30003
