apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 1000M
    nginx.ingress.kubernetes.io/client-body-buffer-size: 1000M



  name: django-app-ingress
  namespace: django-app

spec:
  rules:
    - host: devclouds.live
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: django-app
              port:
                number: 80

