apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: django-app  
  name: django-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: devclouds.live
      http:
        paths:
         - path: /
           pathType: Prefix
           backend:
            service:
              name: django-app-service
              port:
                number: 8000

